# Generated by Django 6.0.3 on 2026-03-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
